// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_F7oRY8Dipzm_xHUW2SJjCMwk1Md135k',
    appId: '1:797942908868:web:cd201d693556fc1e708691',
    messagingSenderId: '797942908868',
    projectId: 'ecommerce-a4b20',
    authDomain: 'ecommerce-a4b20.firebaseapp.com',
    storageBucket: 'ecommerce-a4b20.appspot.com',
    measurementId: 'G-LW4GJ9353N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeCj3iuB8Kb7iKAnhWeFwemSasXFpS39o',
    appId: '1:797942908868:android:0afae74a601d3541708691',
    messagingSenderId: '797942908868',
    projectId: 'ecommerce-a4b20',
    storageBucket: 'ecommerce-a4b20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGOUauAER27x2ZzGLGP8qZkhkQJ2-17Ng',
    appId: '1:797942908868:ios:2739224e7a5006bc708691',
    messagingSenderId: '797942908868',
    projectId: 'ecommerce-a4b20',
    storageBucket: 'ecommerce-a4b20.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGOUauAER27x2ZzGLGP8qZkhkQJ2-17Ng',
    appId: '1:797942908868:ios:8b15e69912aa46d9708691',
    messagingSenderId: '797942908868',
    projectId: 'ecommerce-a4b20',
    storageBucket: 'ecommerce-a4b20.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
